services:

  user:
    container_name: 'user'
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user'
      - 'SPRING_DATASOURCE_USERNAME=root'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    ports:
      - '3000:8080'
    restart: unless-stopped

  postgres:
    container_name: 'postgres'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=user'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
    restart: unless-stopped

